### ISSUE TITLE
not sure if this is the right place (can't ride horse bug?)

### ISSUE THREAD

**Issue by Ozma777** [NHTangles/GruntHack#10]
Windows GruntHack graphical Beta Version 0.2.0-0 - last build Thu Mar 15
15:14:20 2012. [ alpha 0]--More--

An Ogre Wizard #ride to a Saddled Horse (not a pony) it says "you can't ride such a creature."
Is it because I am too large as an ogre, or is it a bug?

**Comment by k21971** [comment]
Hi Ozma777,

Ogres and giants cannot ride steeds by design, they don't fit in the saddle. See src/steed.c around line 246.
