### ISSUE TITLE
Crash? in top level of sanctum

### ISSUE THREAD

**Issue by ChristopherAIguy** [NHTangles/GruntHack#11]
Last night at ~ 21:30 January 1st 2023 EST (2:30 January 2nd 2023 UTC):

Arnibald was steps away from exiting Grunthack's Sanctum with the Amulet.

Rodney showed up with his gang of hooligans, "So you thought..", you know, the whole spiel.  
Arnibald backed up into the narrower corridor and traded his ring of conflict for a second highly enchanted ring of damage.
Some fighting happened, mostly killing of monsters that kept interposing themselves between the chokepoint (and Rodney!) and Arnibald.  There was some funny activity amongst the gang Rodney ported in with, left over from the grudges built up over the previous conflict. So much fun.

Then Rodney stepped up, and gamely took 3 consecutive double-weapon, +20 (considering weapon's enchantment and rings) hits.  After the last, he punched Arnibald, and cast cancellation.

I think I had to hit [space] to acknowledge that Excalibur resisted, and then I was abruptly looking at the Hardfought (US) main menu.

There's no saved game.

The last TTYREC (besides the one I created checking for the saved game), https://www.hardfought.org/nh/gh/trd-us/?file=https://www.hardfought.org/userdata/a/arnibald/gh/ttyrec/2024-01-02.02:17:38.ttyrec.gz contains Arnibald's trek from the Wizard's Tower to the Sanctum and the near escape and abrupt end.

Unfortunately, I think the crash means the TTYREC only has a reference frame in the middle of the TTYREC, so when you hit the [END] button on the web TTYREC player, you then have something like 1000 frames to single step to get to the crash.  I hope you have a better viewer.  I hit the mouse button and space bar that many times but wouldn't expect you to!

Pertinent details from my (motivated) perusal of final frames:

I was in melee with only one party, the Wizard of Yendor.  I whacked him 3 times (x2) good.  His final swipe included a punch, and his cancellation spell which did hit and Excalibur resisted, but also one of my armor's enchantment dropped from +5 to +0, based on the impact on my AC.  Then the last frame or two included a named humanoid "the invisible Andreas" melee-ing a water elemental,  "The invisible Andreas slashes the water elemental.  The long sword of frost freezes the water elemental!"

I had dropped the 3 invocation items right after obtaining the Amulet, so they were out of the picture when the crash occurred.
I don't think it was a panic, because I didn't see any messages.  Until I viewed the TTYREC, I blamed Rodney's cancel of something in inventory for causing the crash.  After viewing the TTYREC, I believe it's possible the 3rd party attack of the invisible Andreas on the water elemental or the anticipated but unmessaged response (water elemental swallowing Andreas?) that caused the crash.

**Comment by ChristopherAIguy** [comment]
Oh, and if possible, I'd really appreciate if my saved file could somehow be recovered.  I've never ascended Grunthack before...

I was on Hardfought US, BTW.

**Comment by k21971** [comment]
Just recovered your game. FYI, the grunthack repo used on the hardfought servers can be found here - https://github.com/k21971/GruntHack

Any future issues, email me direct at admin@hardfought.org - good luck with your game!
